version: "3"

server:
  command: "php /app/public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "/app/public"
    forbid: [ ".php", ".htaccess" ]

status:
  address: localhost:2114

logs:
  mode: production
  channels:
    http:
      level: debug
    server:
      level: info
      mode: raw
    metrics:
      level: error
